version: '2.4'

services:
  web:
    extends:
      file: ../docker-compose.base.yml
      service: web
    env_file: .env
    volumes:
      - "../app:/app"
    depends_on:
      - redis
      - celery
    networks:
      - dev
    command: bash -c "python wait-for-db.py -u mysql+pymysql://${MYSQL_WORDNET_ROOT_USERNAME}:${MYSQL_WORDNET_ROOT_PASSWORD}@${MYSQL_WORDNET_HOST}:3306/${MYSQL_WORDNET_DATABASE} -t 1200 &&
      python wait-for-db.py -u mysql+pymysql://${MYSQL_USERS_ROOT_USERNAME}:${MYSQL_USERS_ROOT_PASSWORD}@${MYSQL_USERS_HOST}:3306/${MYSQL_USERS_DATABASE} -t 30 &&
      python wait-for-db.py -u mysql+pymysql://${MYSQL_TRACKER_ROOT_USERNAME}:${MYSQL_TRACKER_ROOT_PASSWORD}@${MYSQL_TRACKER_HOST}:3306/${MYSQL_TRACKER_DATABASE} -t 30 &&
      gunicorn -c 'python:config.gunicorn' --reload 'tracker.app:create_app()'"
  redis:
    image: redis:5.0.0-alpine
    ports:
      - "6379"
    networks:
      - dev
  celery:
    image: app
    env_file: .env
    volumes:
    - "../app:/app"
    depends_on:
      - redis
    networks:
      - dev
    command: bash -c "python wait-for-db.py -u mysql+pymysql://${MYSQL_WORDNET_ROOT_USERNAME}:${MYSQL_WORDNET_ROOT_PASSWORD}@${MYSQL_WORDNET_HOST}:3306/${MYSQL_WORDNET_DATABASE} -t 1200 &&
      python wait-for-db.py -u mysql+pymysql://${MYSQL_USERS_ROOT_USERNAME}:${MYSQL_USERS_ROOT_PASSWORD}@${MYSQL_USERS_HOST}:3306/${MYSQL_USERS_DATABASE} -t 30 &&
      python wait-for-db.py -u mysql+pymysql://${MYSQL_TRACKER_ROOT_USERNAME}:${MYSQL_TRACKER_ROOT_PASSWORD}@${MYSQL_TRACKER_HOST}:3306/${MYSQL_TRACKER_DATABASE} -t 30 &&
      python celery_start.py"
  celerybeat:
    image: app
    env_file: .env
    volumes:
    - "../app:/app"
    depends_on:
    - redis
    networks:
    - dev
    command: bash -c "python wait-for-db.py -u mysql+pymysql://${MYSQL_WORDNET_ROOT_USERNAME}:${MYSQL_WORDNET_ROOT_PASSWORD}@${MYSQL_WORDNET_HOST}:3306/${MYSQL_WORDNET_DATABASE} -t 1200 &&
      python wait-for-db.py -u mysql+pymysql://${MYSQL_USERS_ROOT_USERNAME}:${MYSQL_USERS_ROOT_PASSWORD}@${MYSQL_USERS_HOST}:3306/${MYSQL_USERS_DATABASE} -t 30 &&
      python wait-for-db.py -u mysql+pymysql://${MYSQL_TRACKER_ROOT_USERNAME}:${MYSQL_TRACKER_ROOT_PASSWORD}@${MYSQL_TRACKER_HOST}:3306/${MYSQL_TRACKER_DATABASE} -t 30 &&
      python celerybeat_start.py"
networks:
  dev:
    name: dev_network
    driver: bridge